# Generated by Django 5.1.7 on 2025-04-01 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Наименование"),
                ),
                (
                    "order_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Цена при оформлении",
                    ),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Цена при покупке",
                    ),
                ),
                (
                    "exchange",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="Вес"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "track_num",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                ("buyed_at", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Созданно"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="order.customer"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="order.purchase"
                    ),
                ),
            ],
        ),
    ]
