# Generated by Django 5.1.7 on 2025-04-01 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buyed_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="buy_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Цена покупки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Созданно"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Заказчик",
                to="order.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Закупка",
                to="order.purchase",
            ),
        ),
    ]
