# Generated by Django 5.1.7 on 2025-04-01 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_buyed_at_alter_order_buy_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("name",),
                "verbose_name": "Клиента",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tg_id",
        ),
        migrations.AddField(
            model_name="customer",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создан"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
