# Generated by Django 5.1.7 on 2025-04-01 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_customer_options_remove_customer_tg_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Закупка",
                "verbose_name_plural": "Закупки",
            },
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\+?\\d{1,3})?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{2}[-.\\s]?\\d{2}$",
                        "Номер телефона некорректен! Формат ввода +7(777) 777-77-77",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=(?:[0-9_]*[a-z]){3})[a-z0-9_]{5,}$",
                        "Telegram ID некоректен!",
                    )
                ],
                verbose_name="Telegram ID",
            ),
        ),
    ]
