# Generated by Django 5.1.7 on 2025-04-01 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_purchase_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("name",),
                "verbose_name": "запись",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("created_at",),
                "verbose_name": "запись",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="purchase",
            options={
                "ordering": ("opened_date",),
                "verbose_name": "запись",
                "verbose_name_plural": "Закупки",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Наименование товара"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Инициатор",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="closed_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата закрытия"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="opened_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата открытия"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Идентификатор"
            ),
        ),
    ]
