# Generated by Django 5.1.7 on 2025-04-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_customer_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "Маркетплейсы",
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="marketplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Маркетплейс",
                to="order.marketplace",
            ),
        ),
    ]
