# Generated by Django 5.1.7 on 2025-04-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_marketplace_order_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/orders"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="order.customer",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="exchange",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Курс при покупке",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="marketplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="order.marketplace",
                verbose_name="Маркетплейс",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="order.purchase",
                verbose_name="Закупка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="track_num",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Трек номер"
            ),
        ),
    ]
