# Generated by Django 5.1.7 on 2025-04-16 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_order_img_alter_order_customer_alter_order_exchange_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tax",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Комиссия",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/orders",
                verbose_name="Изображение товара",
            ),
        ),
    ]
