# Generated by Django 5.1.7 on 2025-04-16 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_customer_tax_alter_order_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="tax",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Комиссия",
            ),
        ),
    ]
