# Generated by Django 5.1.7 on 2025-04-17 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_customer_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="dilivery_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сумма доставки",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Вес посылки",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Номер в формате +7(xxx)xxx-xx-xx",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\+?\\d{1,3})?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{2}[-.\\s]?\\d{2}$",
                        "Номер телефона некорректен! Формат ввода +7(777) 777-77-77",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tax",
            field=models.IntegerField(
                default=0,
                help_text="Комиссия (в процентах), взымаемая с клиента",
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Комиссия %",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор telegram (символы после @)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=(?:[0-9_]*[a-z]){3})[a-z0-9_]{5,}$",
                        "Telegram ID некоректен!",
                    )
                ],
                verbose_name="Telegram ID",
            ),
        ),
    ]
