# Generated by Django 5.1.7 on 2025-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_alter_purchase_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="dilivery_cost",
        ),
        migrations.AddField(
            model_name="purchase",
            name="dilivery_cost1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Стоимость доставки ТК до Москвы",
                max_digits=10,
                null=True,
                verbose_name="Стоимость доставки МСК",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="dilivery_cost2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Стоимость доставки до пункта назначения",
                max_digits=10,
                null=True,
                verbose_name="Стоимость доставки Севастополь",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="other_expenses",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Инные расходы на посылку",
                max_digits=10,
                null=True,
                verbose_name="Инные расходы",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="closed_date",
            field=models.DateField(
                blank=True,
                help_text="Дата ококнчания закупки",
                null=True,
                verbose_name="Дата закрытия",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="opened_date",
            field=models.DateField(
                blank=True,
                help_text="Дата начала закупки",
                null=True,
                verbose_name="Дата открытия",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="title",
            field=models.CharField(
                help_text="Наименование закупки",
                max_length=200,
                unique=True,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Вес посылки",
                max_digits=7,
                null=True,
                verbose_name="Вес посылки",
            ),
        ),
    ]
