# Generated by Django 5.1.7 on 2025-04-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_remove_purchase_dilivery_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(
                default=False,
                help_text="Доставлен продавцом в транспортную компанию?",
                verbose_name="Доставлен в ТК",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_orders",
                to="order.customer",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="order.purchase",
                verbose_name="Закупка",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="other_expenses",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Инные расходы на закупку",
                max_digits=10,
                null=True,
                verbose_name="Инные расходы",
            ),
        ),
    ]
