# Generated by Django 5.1.7 on 2025-04-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_order_is_delivered_alter_order_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="buy_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Цена покупки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="exchange",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Курс при покупке",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Вес"
            ),
        ),
    ]
