# Generated by Django 5.1.7 on 2025-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_alter_order_buy_price_alter_order_exchange_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False, verbose_name="Доставлен в ТК"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Цена заказа"
            ),
        ),
    ]
