# Generated by Django 5.1.7 on 2025-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_order_url_alter_order_is_delivered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="exchange",
            field=models.DecimalField(
                decimal_places=2,
                default=(12.5),
                help_text="Курс валюты закупки",
                max_digits=5,
                verbose_name="Курс закупки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="buy_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена товара при выкупе",
                max_digits=5,
                verbose_name="Цена покупки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="exchange",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Курс валюты при выкупе",
                max_digits=5,
                verbose_name="Курс при покупке",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена товара при оформлении заказа",
                max_digits=5,
                verbose_name="Цена заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="track_num",
            field=models.CharField(
                blank=True,
                help_text="Номер отслеживания заказа",
                max_length=200,
                null=True,
                verbose_name="Трек номер",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на товар",
                null=True,
                verbose_name="Ссылка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Вес товара",
                null=True,
                verbose_name="Вес",
            ),
        ),
    ]
