# Generated by Django 5.1.7 on 2025-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_purchase_exchange_alter_order_buy_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="other_expenses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Инные расходы на закупку",
                max_digits=10,
                verbose_name="Инные расходы",
            ),
        ),
    ]
