# Generated by Django 5.1.7 on 2025-04-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_purchase_other_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
    ]
