# Generated by Django 5.1.7 on 2025-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Оформлен'), (1, 'Выкуплен'), (2, 'Доставляется в ТК'), (3, 'Доставлен в ТК'), (4, 'Отменен')], default=0, verbose_name='Статус'),
        ),
    ]
