# Generated by Django 5.1.7 on 2025-04-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='title',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL маркетплейса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Оформлен'), (1, 'Выкуплен'), (2, 'Доставляется в ТК'), (3, 'Доставлен в ТК'), (4, 'Прибыл в пункт'), (5, 'Отменен')], default=0, verbose_name='Статус'),
        ),
    ]
