# Generated by Django 5.1.7 on 2025-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_marketplace_title_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL маркетплейса'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='title',
            field=models.CharField(default='NULL', max_length=50, unique=True, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
