# Generated by Django 5.1.7 on 2025-04-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_marketplace_url_alter_marketplace_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена товара при оформлении заказа в ¥', max_digits=5, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(help_text='Ссылка на товар', verbose_name='Ссылка'),
        ),
    ]
