# Generated by Django 5.1.7 on 2025-05-12 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_order_price_alter_order_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Идентификатор telegram (символы после @)', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', 'Telegram ID некоректен!')], verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена товара при выкупе', max_digits=5, verbose_name='Цена выкупа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Курс валюты при выкупе', max_digits=5, verbose_name='Курс выкупа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='order.purchase', verbose_name='Закупка'),
        ),
    ]
