# Generated by Django 5.1.7 on 2025-05-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_order_quantity_alter_customer_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выкупа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Оформлен'), (1, 'Выкуплен'), (2, 'Доставляется в ТК'), (3, 'Доставлен в ТК'), (4, 'Прибыл в пункт')], default=0, verbose_name='Статус'),
        ),
    ]
