# Generated by Django 5.1.7 on 2025-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0026_order_buyed_at_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="buyed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выкупа"
            ),
        ),
    ]
