# Generated by Django 5.1.7 on 2025-08-08 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_buyed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL маркетплейса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена товара при выкупе', max_digits=10, verbose_name='Цена выкупа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Курс валюты при выкупе', max_digits=6, verbose_name='Курс выкупа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена товара при оформлении заказа в ¥', max_digits=10, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Вес товара в граммах', null=True, verbose_name='Вес'),
        ),
    ]
